name: master CI, CD workflow
on: 
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: CI
        run: npm c1
      - name: Test
        run: | 
          npm fszf -- -- no-watch --no-progress --browsers=ChromeHEadlessCI
